In [60]:
from divegame import diveGame, zeroBoard
import pickle
from fatal_flaw import fatalFlaw, getActions
import pdb
from softmaxExplain import findStates2
from datetime import datetime
import random
import pandas
from experiment import reconstructStates
import numpy as np
import math
from categorize import categorize, CorrectionType

In [14]:
stateRollouts = {}

In [15]:
group1States = pickle.load(open('group1States', 'rb'))
group1States = reconstructStates(group1States)
for state in group1States:
    rollouts, values = getActions(state, 1, 200000, allRollouts = True)
    for i in range(len(rollouts)):
        stateRollouts[(state, rollouts[i][0])] = (rollouts[i], values[i])

In [16]:
group2States = pickle.load(open('group2States', 'rb'))
group2States = reconstructStates(group2States)
for state in group2States:
    rollouts, values = getActions(state, 1, 200000, allRollouts = True)
    for i in range(len(rollouts)):
        stateRollouts[(state, rollouts[i][0])] = (rollouts[i], values[i])

In [17]:
group3States = pickle.load(open('group3States', 'rb'))
group3States = reconstructStates(group3States)
for state in group3States:
    rollouts, values = getActions(state, 1, 200000, allRollouts = True)
    for i in range(len(rollouts)):
        stateRollouts[(state, rollouts[i][0])] = (rollouts[i], values[i])

In [18]:
generalTestStates = pickle.load(open('general Test States', 'rb'))
generalTestStates = reconstructStates(generalTestStates)
for state in generalTestStates:
    rollouts, values = getActions(state, 1, 200000, allRollouts = True)
    for i in range(len(rollouts)):
        stateRollouts[(state, rollouts[i][0])] = (rollouts[i], values[i])

In [21]:
bestRollout = {}
for state, action in stateRollouts.keys():
    if state not in bestRollout:
        bestRollout[state] = stateRollouts[(state, action)]
    else:
        if stateRollouts[(state, action)][1] > bestRollout[state][1]:
            bestRollout[state] = stateRollouts[(state, action)]

In [52]:
datas = []
def process(name, expgroup):
    d = {}
    f = open("playdata/" + name, "rb")
    f2 = open("playdata/" + name + "2", "rb")
    data = pickle.load(f)
    data2 = pickle.load(f2)
    d['name'] = name
    d['experiment group'] = expgroup
    d['mistake type'] = data['FatalFlawData'][-1]
    d['group'] = data['group']
    testStates = reconstructStates(pickle.load(open("group" + str(data['group'])+ "States", "rb")))
    total = 0
    for i in range(len(testStates)):
        for j in range(len(testStates)):
            if testStates[i] == data['testStates'][j][0]:
                action = data['testStates'][j][1]
                hRollout = stateRollouts[(testStates[i], action)][0]
                rRollout = bestRollout[testStates[i]][0]
                if hRollout[0] == rRollout[0]:
                    d[i + 1] = None
                else:
                    d[i + 1] = categorize(testStates[i], action, rRollout, hRollout)
    testStates = reconstructStates(pickle.load(open("General Test States", "rb")))
    for i in range(6, 12):
        for j in range(6):
            if testStates[i - 6] == data2['testStates'][j][0]:
                action = data2['testStates'][j][1]
                hRollout = stateRollouts[(testStates[i - 6], action)][0]
                rRollout = bestRollout[testStates[i - 6]][0]
                if hRollout[0] == rRollout[0]:
                    d[i + 1] = None
                else:
                    d[i + 1] = categorize(testStates[i - 6], action, rRollout, hRollout)
    datas.append(d)

    
    

process("calvin", "short explanation")
process("raymond", "short explanation")
process("kenneth", "short explanation")
process("sam", "short explanation")
process("stanley", "short explanation")
process("arvin", "short explanation")
process("hong", "short explanation")



process("aayush", "long explanation")
process("karthik", "long explanation")
process("nadir", "long explanation")
process("rustie", "long explanation")
process("andy", "long explanation")
process("gokul", "long explanation")


process("jonny", "no explanation")
process("alex", "no explanation")
process("ket", "no explanation")
process("charlie", "no explanation")
process("aakash", "no explanation")
process("neel", "no explanation")
process("kartik", "no explanation")
process("sera", "no explanation")
process("jinsu", "no explanation")


df = pandas.DataFrame(datas)

In [55]:
df

,experiment group,group,mistake type,name,1,2,3,4,5,6,7,8,9,10,11,12
0,short explanation,1,CorrectionType.J,calvin,None,None,None,None,CorrectionType.J,CorrectionType.C4,None,None,None,CorrectionType.C3,CorrectionType.I,None
1,short explanation,1,CorrectionType.J,raymond,None,None,None,None,CorrectionType.J,None,CorrectionType.A,None,None,CorrectionType.C3,CorrectionType.I,None
2,short explanation,1,CorrectionType.J,kenneth,None,CorrectionType.C3,None,CorrectionType.A,CorrectionType.J,CorrectionType.C3,CorrectionType.A,None,None,CorrectionType.E,CorrectionType.I,CorrectionType.C3
3,short explanation,1,CorrectionType.B,sam,None,None,None,None,CorrectionType.J,None,CorrectionType.A,None,CorrectionType.D,CorrectionType.C3,CorrectionType.I,CorrectionType.C3
4,short explanation,3,CorrectionType.I,stanley,CorrectionType.I,CorrectionType.I,CorrectionType.C4,None,None,CorrectionType.C3,None,None,None,CorrectionType.C3,None,None
5,short explanation,2,CorrectionType.E,arvin,None,None,None,None,CorrectionType.C3,CorrectionType.F,CorrectionType.A,CorrectionType.J,None,CorrectionType.E,CorrectionType.I,CorrectionType.C3
6,short explanation,1,CorrectionType.A,hong,None,None,CorrectionType.J,CorrectionType.A,CorrectionType.J,CorrectionType.C4,CorrectionType.A,None,None,CorrectionType.C3,CorrectionType.I,CorrectionType.C3
7,long explanation,1,CorrectionType.A,aayush,None,CorrectionType.C3,None,CorrectionType.A,CorrectionType.J,None,None,None,CorrectionType.D,CorrectionType.C3,CorrectionType.I,None
8,long explanation,2,CorrectionType.E,karthik,None,None,None,None,CorrectionType.C3,None,CorrectionType.A,CorrectionType.J,CorrectionType.D,CorrectionType.C3,CorrectionType.I,None
9,long explanation,2,CorrectionType.E,nadir,None,CorrectionType.C3,None,CorrectionType.D,CorrectionType.C3,None,None,None,None,CorrectionType.C3,CorrectionType.I,None
10,long explanation,1,CorrectionType.B,rustie,CorrectionType.A,CorrectionType.A,CorrectionType.C3,CorrectionType.A,CorrectionType.C3,CorrectionType.C3,CorrectionType.A,CorrectionType.C3,CorrectionType.D,CorrectionType.C3,CorrectionType.I,CorrectionType.C3
11,long explanation,1,CorrectionType.J,andy,None,None,CorrectionType.J,CorrectionType.A,None,None,CorrectionType.A,CorrectionType.J,CorrectionType.D,CorrectionType.C3,CorrectionType.I,CorrectionType.C3
12,long explanation,1,CorrectionType.A,gokul,None,None,None,CorrectionType.B,None,None,CorrectionType.A,None,CorrectionType.D,CorrectionType.C3,CorrectionType.I,None
13,no explanation,3,CorrectionType.K,jonny,CorrectionType.I,CorrectionType.I,CorrectionType.C3,CorrectionType.I,CorrectionType.C1,CorrectionType.C3,CorrectionType.A,None,None,CorrectionType.C3,None,CorrectionType.C3
14,no explanation,1,CorrectionType.A,alex,None,CorrectionType.C4,CorrectionType.J,CorrectionType.B,None,None,CorrectionType.A,CorrectionType.J,CorrectionType.D,CorrectionType.C3,None,CorrectionType.K
15,no explanation,2,CorrectionType.E,ket,None,None,CorrectionType.D,None,CorrectionType.E,None,CorrectionType.A,None,None,CorrectionType.E,CorrectionType.I,None
16,no explanation,2,CorrectionType.D,charlie,CorrectionType.D,CorrectionType.C3,None,CorrectionType.D,CorrectionType.C3,CorrectionType.D,CorrectionType.A,None,None,CorrectionType.C3,CorrectionType.I,None
17,no explanation,2,CorrectionType.E,aakash,None,CorrectionType.C3,None,None,CorrectionType.E,None,CorrectionType.B,None,None,CorrectionType.C3,None,None
18,no explanation,1,CorrectionType.A,neel,None,None,CorrectionType.J,None,CorrectionType.J,CorrectionType.C4,CorrectionType.A,None,None,CorrectionType.E,CorrectionType.I,None
19,no explanation,1,CorrectionType.B,kartik,None,CorrectionType.C3,None,CorrectionType.B,CorrectionType.J,None,CorrectionType.A,None,CorrectionType.D,CorrectionType.C3,CorrectionType.I,CorrectionType.C3
20,no explanation,2,CorrectionType.E,sera,CorrectionType.D,None,None,None,CorrectionType.C3,None,CorrectionType.A,None,CorrectionType.D,CorrectionType.E,CorrectionType.I,None
21,no explanation,2,CorrectionType.E,jinsu,None,CorrectionType.E,None,CorrectionType.D,CorrectionType.E,None,None,None,None,CorrectionType.C3,CorrectionType.I,None

In [66]:
group1 = df[(df['mistake type'] == CorrectionType.E)][['experiment group', 'name', 'mistake type', 'group', 1, 2, 3, 4, 5, 6, 9, 10]]
group1

,experiment group,name,mistake type,group,1,2,3,4,5,6,9,10
5,short explanation,arvin,CorrectionType.E,2,None,None,None,None,CorrectionType.C3,CorrectionType.F,None,CorrectionType.E
8,long explanation,karthik,CorrectionType.E,2,None,None,None,None,CorrectionType.C3,None,CorrectionType.D,CorrectionType.C3
9,long explanation,nadir,CorrectionType.E,2,None,CorrectionType.C3,None,CorrectionType.D,CorrectionType.C3,None,None,CorrectionType.C3
15,no explanation,ket,CorrectionType.E,2,None,None,CorrectionType.D,None,CorrectionType.E,None,None,CorrectionType.E
17,no explanation,aakash,CorrectionType.E,2,None,CorrectionType.C3,None,None,CorrectionType.E,None,None,CorrectionType.C3
20,no explanation,sera,CorrectionType.E,2,CorrectionType.D,None,None,None,CorrectionType.C3,None,CorrectionType.D,CorrectionType.E
21,no explanation,jinsu,CorrectionType.E,2,None,CorrectionType.E,None,CorrectionType.D,CorrectionType.E,None,None,CorrectionType.C3

In [68]:
group1 = df[(df['mistake type'] == CorrectionType.A)][['experiment group', 'name', 'mistake type', 'group', 1, 2, 3, 4, 5, 6, 7, 8]]
group1

,experiment group,name,mistake type,group,1,2,3,4,5,6,7,8
6,short explanation,hong,CorrectionType.A,1,None,None,CorrectionType.J,CorrectionType.A,CorrectionType.J,CorrectionType.C4,CorrectionType.A,None
7,long explanation,aayush,CorrectionType.A,1,None,CorrectionType.C3,None,CorrectionType.A,CorrectionType.J,None,None,None
12,long explanation,gokul,CorrectionType.A,1,None,None,None,CorrectionType.B,None,None,CorrectionType.A,None
14,no explanation,alex,CorrectionType.A,1,None,CorrectionType.C4,CorrectionType.J,CorrectionType.B,None,None,CorrectionType.A,CorrectionType.J
18,no explanation,neel,CorrectionType.A,1,None,None,CorrectionType.J,None,CorrectionType.J,CorrectionType.C4,CorrectionType.A,None

In [69]:
group1 = df[(df['mistake type'] == CorrectionType.B)][['experiment group', 'name', 'mistake type', 'group', 1, 2, 3, 4, 5, 6, 7, 8]]
group1

,experiment group,name,mistake type,group,1,2,3,4,5,6,7,8
3,short explanation,sam,CorrectionType.B,1,None,None,None,None,CorrectionType.J,None,CorrectionType.A,None
10,long explanation,rustie,CorrectionType.B,1,CorrectionType.A,CorrectionType.A,CorrectionType.C3,CorrectionType.A,CorrectionType.C3,CorrectionType.C3,CorrectionType.A,CorrectionType.C3
19,no explanation,kartik,CorrectionType.B,1,None,CorrectionType.C3,None,CorrectionType.B,CorrectionType.J,None,CorrectionType.A,None

In [70]:
f = open("state rollouts", 'wb')
pickle.dump(stateRollouts, f)
f.close()